### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by rzerres** [terry90/internationalization-rs#1]
# Abstract

I'm using this crate in a rust application.
I compiles fine under linux. In most cases it works out if i install on a clean environment. LANG enviroment is 
configured to be default (ala C) or a UTF8 derivate (de_DE.UTF8, en_EN.UTF8).

# Problems
Sometimes, but not reproducable i have encounterd a problem, if i have introduced new translacions and need to rerun with 
cargo. If it fails, the error message found will go like this:

``` bash
error: failed to run custom build command for `locales v0.1.0`
```
To overcome, i do delete the locales compile subfolder in /target and restart. If that doesn't work, i do a 

``` bash
cargo clean;
cargo build
```
The used translations are in a locales subfolder in projetcs root. Following your documentation,
the regex search should always find the given locals. Right now, i have support for English (en)  as well as German (de, de_DE.UTF-8). 

# Windows

One main objective for the Project is to compile under Windows. And i can't make it work. It always fails with the error

``` bash
error: failed to run custom build command for `locales v0.1.0`
```
I did test with globaly set variable  LANG (de, en, de_DE.UTF8) using Microsofts system environment. When i open a new dos-BOX and check the given env (using set) it seems to be fine. That should all that is needed for locales, right?

``` bash
LANG=de 
```

# Questions

* WINDOWS requirements
did you test it to be working on Windows? Am I missing an obvious thing?

* ALIASES
It's not clear to me, if the macro t! is able to solve aliases.  

* Disabling Locales
if locales can't compile, it renders the project completely useless. Is there an easy adoptable path to compile without language support (e.g like a feature that can be disables). It should completely ignore the t! macro.  

Thanks for providing locales ...
Ralf

**Comment by terry90** [comment]
Could you please check the `PWD` env var ? It has to be present

**Comment by rzerres** [comment]
Thanks for the response.
But the hint is not solving the problem. Env `PWD` is set.

**Comment by terry90** [comment]
Could you please provide a stacktrace ? I do not work with windows.

Edit: Nvm I installed mingw and cross compiled on my machine, but I successfully compiled my project, no issue with `locales`

**Comment by rzerres** [comment]
Sorry on replying that late....
I could solve the issue. As you said, the crate is relying on the availibility of a `PWD` environment variable.
Windows does not offer this out of the box. When using git-bash (from the windows git package), the shell will handle the `PWD`. And the compile will work out with no problems. In a `cargo build` call, the macro can resolve the constants and the resulting binary will be created as expected.

The issue is solved. You may add this hint in the README.md

Cheers
Ralf
