### ISSUE TITLE
failed to run custom build command for `locales v0.1.0`

### ISSUE THREAD

**Issue by hgx** [terry90/internationalization-rs#2]
When the project has the same "locales" directory under "node_models", the build fails.

![image](https://user-images.githubusercontent.com/34025950/139832468-4fa1a8d2-88f5-4658-a6d0-5cf5543ae93f.png)

file: node_modules/terser-webpack-plugin/node_modules/cacache/locales/en.json
![image](https://user-images.githubusercontent.com/34025950/139833080-e9c70440-6187-4d91-81a5-4682411fa837.png)

**Comment by terry90** [comment]
Indeed, this crate uses a glob pattern to be flexible enough and match any locales folder in the project. I'll be happy to accept a pull request with a configurable pattern if you're willing to.
